### ISSUE TITLE
Function breaks when trying to evaluate regex patterns against number values via match

### ISSUE THREAD

**Issue by aymanfarhat** [mena-devs/objectron#10]
### Payload

```
{
   response: {
      status: 200
  }
}
```

### Pattern

```
{
  response: {
    status: /\d*/
}
```

Instead of getting the expected match result, the function breaks returning the error `TypeError: payload[key].match is not a function`. This is because match is being called via the number value while it doesn't exist since number isn't an object nor has it within its prototype. 

An alternative to fix this would be to call `exec` on the regex pattern itself. e.g. `value.exec(payload[key])` (when value is a RegExp) instead of `payload[key].match(value)`

**Comment by Link-** [comment]
Fixed in #12
