### ISSUE TITLE
Array of object patterns not matching properly against payload if indexes are different

### ISSUE THREAD

**Issue by aymanfarhat** [mena-devs/objectron#14]
Based on some usage, I've noticed that objects in an array don't seem to be properly matching with the array of objects in the payload. There is a corner case that can happen when the match object in the payload is not at the same index as that of the pattern. This would lead to wrong evaluation of values or missing an evaluation altogether.

## Example test

```
 test('Match array objects further in the array', () => {
    const payload = {
      response: {
        headers: [
          {
            "name": "accept-ranges",
            "value": "bytes"
          },
          {
            "name": "vary",
            "value": "Accept-Encoding"
          },
          {
            "name": "cache-control",
            "value": "public, max-age=31536000, stale-while-revalidate=2592000"
          },
          {
            "name": "content-encoding",
            "value": "gzip"
          },
        ]
      }
    };

    const result = match(payload, {
      response: {
        headers: [
          { 
            name: 'cache-control', 
            value: /(?<responseHeaderCacheControl>.*)/ 
          },
        ]
      }
    });

    const expected = {
      match: true,
      total: 1,
      matches: {
        response: {
          headers:[
            {
              'name': 'cache-control',
              'value': 'public, max-age=31536000, stale-while-revalidate=2592000'
            },
          ]
        }
      },
      groups: {
        responseHeaderCacheControl: 'public, max-age=31536000, stale-while-revalidate=2592000'
      }
    }

    assert.deepEqual(result, expected);
  });
```

## Test output

```
       {
         "groups": {
      -    "responseHeaderCacheControl": "bytes"
      +    "responseHeaderCacheControl": "public, max-age=31536000, stale-while-revalidate=2592000"
         }
      -  "match": false
      +  "match": true
         "matches": {
           "response": {
             "headers": [
               {
      -          "value": "bytes"
      +          "name": "cache-control"
      +          "value": "public, max-age=31536000, stale-while-revalidate=2592000"
               }
             ]
           }
         }
```

## Analysis 

Looking at the objectron code, I've noticed this is happening because there is an assumption that the matched object in payload should be of the same index and order as that of the one in the pattern. 

Taking a look at [line 47 in the source code](https://github.com/mena-devs/objectron/blob/b48131318a049fb61361329ded97cce0051f3337/index.js#L47), we're looping into the array based on the pattern's array of objects size, then on [line 65](https://github.com/mena-devs/objectron/blob/b48131318a049fb61361329ded97cce0051f3337/index.js#L65) sending the index of the current value (pattern) to test against the payload which might actually be at a totally different index.

**Comment by omaraboumrad** [comment]
> Looking at the objectron code, I've noticed this is happening because there is an assumption that the matched object in payload *should be of the same index and order* as that of the one in the pattern.

We assume arbitrary positions, Set-like contain.

Example test - https://github.com/mena-devs/objectron/blob/master/test/test_objectron.js#L191-L199

That said, I'm fairly certain there are uncovered cases especially with array of objects.

**Comment by aymanfarhat** [comment]
@omaraboumrad Yes I agree, this works well for non object elements in arrays such as strings since `payload[key].includes(element)` is being applied. For Object we will need something similar.

In that scenario, we might have to make sure that we scan the whole contents of the payload array for a match before calling `tester`. Which is what `.includes` is doing on the primitive types.

RegExp in arrays might also have this problem, but I didn't test that one out.

What do you think? Shall I take a stab at it?

**Comment by Link-** [comment]
I added a scenario that demonstrates the above in the test suite with e296accc67f7a85cdd266a11e7debb038794f7d3 

In my opinion this is a feature not necessarily a bug. Super useful to have it resolved. I think it should be a priority item for us to work on.
